# Generated by Django 3.2.12 on 2022-03-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_static', '0002_throttling'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdevice',
            name='hash_algorithm',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='staticdevice',
            name='salt',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='statictoken',
            name='token',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
